### ISSUE TITLE
panic: unreachable (generics)

### ISSUE THREAD

**Issue by powerman** [go-critic/go-critic#1219]
Using latest version 0.6.3 on trivial package with generics https://github.com/powerman/chanq result in panic.

```
$ gocritic check -enable='#diagnostic' 
panic: unreachable [recovered]
	panic: unreachable

goroutine 599 [running]:
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1.1()
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/lintmain/internal/check/check.go:155 +0x11e
panic({0x903ca0, 0xa088c0})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/quasilyte/go-ruleguard/internal/xtypes.typeIdentical({0xa0c430?, 0xc0007cb530?}, {0xa0c318?, 0xc0001c2850?}, 0x0)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/internal/xtypes/xtypes.go:218 +0x645
github.com/quasilyte/go-ruleguard/internal/xtypes.Identical(...)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/internal/xtypes/xtypes.go:57
github.com/quasilyte/go-ruleguard/ruleguard/typematch.(*Pattern).matchIdentical(0xc000245128?, 0xc0015fe010, 0x6bfeee?, {0xa0c430, 0xc0007cb530?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/typematch/typematch.go:439 +0x87f
github.com/quasilyte/go-ruleguard/ruleguard/typematch.(*Pattern).MatchIdentical(0xc0003bc100, 0xc0015fe010, {0xa0c430, 0xc0007cb530})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/typematch/typematch.go:370 +0x15d
github.com/quasilyte/go-ruleguard/ruleguard.makeTypeIsFilter.func2(0xc00011c578)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/filters.go:314 +0x117
github.com/quasilyte/go-ruleguard/ruleguard.makeAndFilter.func1(0x942300?)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/filters.go:45 +0x2e
github.com/quasilyte/go-ruleguard/ruleguard.(*rulesRunner).handleMatch(0xc00011c400, {0xc0001f7760, 0x2c6, 0xc0003bc150, {0x996bbf, 0x34}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/runner.go:340 +0x112
github.com/quasilyte/go-ruleguard/ruleguard.(*rulesRunner).runRules.func1({{0xa0b9b8, 0xc0005e0c80}, {0xc00010e000, 0x3, 0x8}})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/runner.go:243 +0xa5
github.com/quasilyte/gogrep.(*matcher).MatchNode(0xc00033e860, 0xc00011c470, {0xa0b9b8?, 0xc0005e0c80?}, 0xc000245588)
	/home/powerman/go/pkg/mod/github.com/quasilyte/gogrep@v0.0.0-20220120141003-628d8b3623b5/match.go:84 +0x4e3
github.com/quasilyte/gogrep.(*Pattern).MatchNode(...)
	/home/powerman/go/pkg/mod/github.com/quasilyte/gogrep@v0.0.0-20220120141003-628d8b3623b5/gogrep.go:90
github.com/quasilyte/go-ruleguard/ruleguard.(*rulesRunner).runRules(0xc00011c400?, {0xa0b9b8?, 0xc0005e0c80?}, 0x2?)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/runner.go:242 +0x14b
github.com/quasilyte/go-ruleguard/ruleguard.(*rulesRunner).run.func1({0xa0b9b8?, 0xc0005e0c80?}, 0x1?)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/runner.go:157 +0x33
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000245c18, {0xa0b9b8?, 0xc0005e0c80?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:194 +0x19dd
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walkStmtList(0xa0baa8?, {0xc0003d92c0?, 0x2, 0x55c656?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:37 +0x85
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000227c18, {0xa0baa8?, 0xc0007ca780?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:218 +0x1b9e
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000245c18, {0xa0be68?, 0xc0005e0cc0?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:240 +0x1e3b
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walkStmtList(0xa0baa8?, {0xc0003d94c0?, 0x2, 0x400?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:37 +0x85
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000227c18, {0xa0baa8?, 0xc0007ca7b0?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:218 +0x1b9e
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000245c18, {0xa0bd78?, 0xc0007ca7e0?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:360 +0x86a
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walkDeclList(0xc000227c18?, {0xc0005e0d80?, 0x4, 0xc000227b98?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:43 +0x85
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).walk(0xc000227c18, {0xa0bd28?, 0xc0006fe700?})
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:367 +0x121e
github.com/quasilyte/go-ruleguard/ruleguard.(*astWalker).Walk(...)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ast_walker.go:20
github.com/quasilyte/go-ruleguard/ruleguard.(*rulesRunner).run(0xc00011c400, 0xc0006fe700)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/runner.go:156 +0x1c9
github.com/quasilyte/go-ruleguard/ruleguard.(*engine).Run(0x7f9d50d61fff?, 0x577c65?, 0x203000?, 0x400?)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/engine.go:127 +0x45
github.com/quasilyte/go-ruleguard/ruleguard.(*Engine).Run(...)
	/home/powerman/go/pkg/mod/github.com/quasilyte/go-ruleguard@v0.3.16-0.20220213074421-6aa060fab41a/ruleguard/ruleguard.go:74
github.com/go-critic/go-critic/checkers.runRuleguardEngine(0xc0018b4888, 0xc0006fe700, 0xc00073a7f0, 0xc0015fa000)
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/ruleguard_checker.go:301 +0xd9
github.com/go-critic/go-critic/checkers.(*embeddedRuleguardChecker).WalkFile(0xc00073ab70, 0x0?)
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:98 +0xea
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/linter/linter.go:129
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1(0x15, 0xc0018b4880)
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/lintmain/internal/check/check.go:159 +0xc2
created by github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile
	/home/powerman/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/lintmain/internal/check/check.go:141 +0xa5
```

**Comment by cristaloleg** [comment]
Is this still reproducible with v0.6.4 ?

**Comment by quasilyte** [comment]
Should be fixed after we update the ruleguard.
See https://github.com/quasilyte/go-ruleguard/commit/4bff5cbccc0a49e127aba272d65392fabb6071f1
