### ISSUE TITLE
Panic with `paramTypeCombine`

### ISSUE THREAD

**Issue by EwenQuim** [go-critic/go-critic#1248]
The linter panics when enabling `paramTypeCombine` (in #style, disabled by default)

gocritic version used : commit dfd27d0df92629db2ef1c3958ae695e5132c066c (not a release, the master branch as I write this issue)

```
❯ gocritic check -enable='paramTypeCombine' ./...
./services/invitation/mocks/mocks.go:70:1: paramTypeCombine: func(actorID string, eventID string, spaceID string) ([]model.Invitation, error) could be replaced with func(actorID, eventID, spaceID string) ([]model.Invitation, error)
panic: unhandled expr [recovered]
        panic: unhandled expr

goroutine 4049 [running]:
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1.1()
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/framework/lintmain/internal/check/check.go:160 +0x100
panic({0x102de7560, 0x102e79b18})
        /opt/homebrew/Cellar/go/1.19/libexec/src/runtime/panic.go:884 +0x204
github.com/go-toolsmith/astcopy.copyExpr({0x102e7e760?, 0x140017def80?})
        /Users/ewenq/go/pkg/mod/github.com/go-toolsmith/astcopy@v1.0.1/astcopy.go:889 +0x72c
github.com/go-toolsmith/astcopy.Field(0x140017df000)
        /Users/ewenq/go/pkg/mod/github.com/go-toolsmith/astcopy@v1.0.1/astcopy.go:314 +0x1f0
github.com/go-toolsmith/astcopy.FieldList(0x140016af110)
        /Users/ewenq/go/pkg/mod/github.com/go-toolsmith/astcopy@v1.0.1/astcopy.go:331 +0x150
github.com/go-toolsmith/astcopy.FuncType(0x140017ef3c0)
        /Users/ewenq/go/pkg/mod/github.com/go-toolsmith/astcopy@v1.0.1/astcopy.go:347 +0x12c
github.com/go-critic/go-critic/checkers.(*paramTypeCombineChecker).optimizeFuncType(0x102e7e5e0?, 0x140017ef3c0)
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/checkers/paramTypeCombine_checker.go:42 +0x28
github.com/go-critic/go-critic/checkers.(*paramTypeCombineChecker).VisitFuncDecl(0x14000b36f38?, 0x140016af470)
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/checkers/paramTypeCombine_checker.go:35 +0x2c
github.com/go-critic/go-critic/checkers/internal/astwalk.(*funcDeclWalker).WalkFile(0x140021bb780, 0x14001942780)
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/checkers/internal/astwalk/func_decl_walker.go:21 +0xec
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/framework/linter/linter.go:130
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1(0x0, 0x14002341b00)
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/framework/lintmain/internal/check/check.go:164 +0x8c
created by github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile
        /Users/ewenq/go/pkg/mod/github.com/go-critic/go-critic@v0.6.4-0.20220809214914-dfd27d0df926/framework/lintmain/internal/check/check.go:146 +0x80
```

**Comment by quasilyte** [comment]
I'll fix this problem in astcopy package.
Thank you for reporting this.

**Comment by quasilyte** [comment]
https://github.com/go-toolsmith/astcopy/releases/tag/v1.0.2
