### ISSUE TITLE
rangValCopy panics on code with generics

### ISSUE THREAD

**Issue by ryancurrah** [go-critic/go-critic#1297]
The `rangeValCopy` check panics on code with generics.

```bash
╰─ gocritic check -@rangeValCopy.sizeThreshold 1024 -enable='rangeValCopy' ./internal/pkg/cache/...
panic: assertion failed [recovered]
        panic: assertion failed

goroutine 6559 [running]:
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1.1()
        /Users/rcurrah/go-critic/framework/lintmain/internal/check/check.go:160 +0x11e
panic({0x1003fd660, 0x1005221b0})
        /Users/rcurrah/.go/current/src/runtime/panic.go:838 +0x207
go/types.assert(...)
        /Users/rcurrah/.go/current/src/go/types/errors.go:21
go/types.(*StdSizes).Alignof(0xc000132210, {0x1005250a8?, 0xc002ab1e00})
        /Users/rcurrah/.go/current/src/go/types/sizes.go:72 +0x25f
go/types.(*StdSizes).Offsetsof(0x100524f90?, {0xc0003a73d0, 0x2, 0x0?})
        /Users/rcurrah/.go/current/src/go/types/sizes.go:101 +0xdd
go/types.(*StdSizes).Sizeof(0xc000132210, {0x100524f90?, 0xc002883d50})
        /Users/rcurrah/.go/current/src/go/types/sizes.go:154 +0x1c5
github.com/go-critic/go-critic/framework/linter.(*CheckerContext).SizeOf(...)
        /Users/rcurrah/go-critic/framework/linter/linter.go:333
github.com/go-critic/go-critic/checkers.(*rangeValCopyChecker).VisitStmt(0xc002aa1a60, {0x1005260e0?, 0xc0028c3f40?})
        /Users/rcurrah/go-critic/checkers/rangeValCopy_checker.go:72 +0xcb
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile.func1({0x100524c98?, 0xc0028c3f40?})
        /Users/rcurrah/go-critic/checkers/internal/astwalk/stmt_walker.go:23 +0x62
go/ast.inspector.Visit(0xc002b9e0a0, {0x100524c98?, 0xc0028c3f40?})
        /Users/rcurrah/.go/current/src/go/ast/walk.go:387 +0x31
go/ast.Walk({0x100523e60?, 0xc002b9e0a0?}, {0x100524c98?, 0xc0028c3f40?})
        /Users/rcurrah/.go/current/src/go/ast/walk.go:52 +0x62
go/ast.walkStmtList({0x100523e60, 0xc002b9e0a0}, {0xc0027e0d80?, 0x6, 0x12823f388?})
        /Users/rcurrah/.go/current/src/go/ast/walk.go:32 +0x91
go/ast.Walk({0x100523e60?, 0xc002b9e0a0?}, {0x100524720?, 0xc0028f6150?})
        /Users/rcurrah/.go/current/src/go/ast/walk.go:235 +0x10e5
go/ast.Inspect(...)
        /Users/rcurrah/.go/current/src/go/ast/walk.go:399
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile(0xc001e2dec0?, 0xc0027e0e80?)
        /Users/rcurrah/go-critic/checkers/internal/astwalk/stmt_walker.go:21 +0x12c
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
        /Users/rcurrah/go-critic/framework/linter/linter.go:130
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1(0x0, 0xc001f37240)
        /Users/rcurrah/go-critic/framework/lintmain/internal/check/check.go:164 +0xc2
created by github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile
        /Users/rcurrah/go-critic/framework/lintmain/internal/check/check.go:146 +0xa5
```

**Comment by cristaloleg** [comment]
Fixed in https://github.com/go-critic/go-critic/pull/1309
