### ISSUE TITLE
bug: `rangeValCopy` still panics on code with generics

### ISSUE THREAD

**Issue by korya** [go-critic/go-critic#1354]
The check `rangeValCopy` panics when run on code using generics.

### Version

I've installed the latest version using:

```
go install -v github.com/go-critic/go-critic/cmd/gocritic
```

The output of `gocritic version` is not particularly useful:

```
$ gocritic version
gocritic version: v0.0.0-SNAPSHOT
```

### The Panic

The problem can be reproduced on https://github.com/korya/issue-gocritic-rangeValCopy. The result is:

```
$  gocritic check -enable rangeValCopy .
panic: /opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/sizes.go:82: assertion failed [recovered]
	panic: /opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/sizes.go:82: assertion failed

goroutine 856 [running]:
main.(*program).checkFile.func1.1()
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/cmd/gocritic/check.go:168 +0x114
panic({0x104b02c80, 0x140003a22c0})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/runtime/panic.go:884 +0x204
go/types.assert(0xc8?)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/errors.go:28 +0x60
go/types.(*StdSizes).Alignof(0x140000a63b0, {0x104b7edc8?, 0x1400031c270})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/sizes.go:82 +0xfc
go/types.(*StdSizes).Offsetsof(0x104b7ed78?, {0x14000bca820, 0x2, 0x14000d90b90?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/sizes.go:123 +0xc8
go/types.(*StdSizes).Sizeof(0x140000a63b0, {0x104b7ed78?, 0x1400031cb10})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/types/sizes.go:176 +0x1c8
github.com/go-critic/go-critic/linter.(*CheckerContext).SizeOf(0x14000da5db0?, {0x104b7ed78?, 0x1400031cb10?})
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/linter/linter.go:353 +0xac
github.com/go-critic/go-critic/checkers.(*rangeValCopyChecker).VisitStmt(0x14000549640, {0x104b7f8c8?, 0x140013e5200?})
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/checkers/rangeValCopy_checker.go:68 +0x98
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile.func1({0x104b7e9b8?, 0x140013e5200?})
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/checkers/internal/astwalk/stmt_walker.go:23 +0x60
go/ast.inspector.Visit(0x140003a2290, {0x104b7e9b8?, 0x140013e5200?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/ast/walk.go:386 +0x38
go/ast.Walk({0x104b7dbd8?, 0x140003a2290?}, {0x104b7e9b8?, 0x140013e5200?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/ast/walk.go:51 +0x4c
go/ast.walkStmtList({0x104b7dbd8, 0x140003a2290}, {0x14000548c00?, 0x2, 0x1400005f608?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/ast/walk.go:32 +0x64
go/ast.Walk({0x104b7dbd8?, 0x140003a2290?}, {0x104b7e440?, 0x14000133710?})
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/ast/walk.go:234 +0xce0
go/ast.Inspect(...)
	/opt/homebrew/Cellar/go/1.20.5/libexec/src/go/ast/walk.go:397
github.com/go-critic/go-critic/checkers/internal/astwalk.(*stmtWalker).WalkFile(0x140003a2240, 0x14000128f30)
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/checkers/internal/astwalk/stmt_walker.go:21 +0x138
github.com/go-critic/go-critic/linter.(*Checker).Check(...)
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/linter/linter.go:159
main.(*program).checkFile.func1()
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/cmd/gocritic/check.go:172 +0x94
created by main.(*program).checkFile
	/Users/dmitri/go/pkg/mod/github.com/go-critic/go-critic@v0.8.1/cmd/gocritic/check.go:152 +0x94
```

### Similar Issues

I found a similar issue dated back in January 2023, https://github.com/go-critic/go-critic/issues/1297, but it got fixed in February. The latest master should contain this fix. So it is not a duplicate.

**Comment by cristaloleg** [comment]
Thanks for the report, I will take a look on Wednesday. Unless you're eager to make a fix.

**Comment by korya** [comment]
Thanks!

**Comment by cristaloleg** [comment]
https://github.com/go-critic/go-critic/releases/tag/v0.8.2
