### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by adamdecaf** [go-critic/go-critic#617]
Hey! I was trying to run this linter on [`github.com/moov-io/ach`](https://github.com/moov-io/ach), but ran into the following panic.

I've tried on windows and linux, but both panic, both are on Go 1.11.

```
C:\Users\adam\go\bin>gocritic.exe check-package -enable=all -withExperimental -withOpinionated github.com/moov-io/ach
fatal error: concurrent map writes

goroutine 539 [running]:
runtime.throw(0x85c0e0, 0x15)
        C:/Go/src/runtime/panic.go:608 +0x79 fp=0xc00a009de0 sp=0xc00a009db0 pc=0x42cd99
runtime.mapassign_fast64ptr(0x7da860, 0xc006586cc0, 0xc0073f9ce0, 0xc003a4fad8)
        C:/Go/src/runtime/map_fast64.go:258 +0x314 fp=0xc00a009e20 sp=0xc00a009de0 pc=0x4111d4
github.com/go-critic/go-critic/lint.resolvePkgObjects(0xc00949a7d0, 0xc0002b8400)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/lint/lint_private.go:208 +0x287 fp=0xc00a009eb0 sp=0xc00a009e20 pc=0x762cf7
github.com/go-critic/go-critic/lint.(*Checker).Check(0xc00949b2c0, 0xc0002b8400, 0xc00947ffe4, 0xc00949b2c0, 0x0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/lint/lint.go:96 +0xc6 fp=0xc00a009ed0 sp=0xc00a009eb0 pc=0x761f36
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949b2c0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:290 +0x9b fp=0xc00a009fc0 sp=0xc00a009ed0 pc=0x78065b
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00a009fc8 sp=0xc00a009fc0 pc=0x456af1
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00947ffe4)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc00947ffe4)
        C:/Go/src/sync/waitgroup.go:130 +0x6b
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile(0xc0000cbdc0, 0xc0002b8400)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:300 +0xde
github.com/go-critic/go-critic/cmd/criticize.(*linter).CheckPackage(0xc0000cbdc0, 0xc000064100, 0x16)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:241 +0x1bd
github.com/go-critic/go-critic/cmd/criticize.Main()
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:102 +0xd4
main.main()
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/gocritic/main.go:68 +0x1c0

goroutine 520 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949ab90)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 530 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949afa0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 514 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949a9b0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 518 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949aaf0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 517 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949aaa0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 529 [runnable]:
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc00947ffe4, 0xc0002b8400, 0xc0000cbdc0, 0xc00949af50)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3
```

**Comment by Quasilyte** [comment]
Seems like you've tried `-withExperimental`.
I suggest disabling `longChain` checker with `-disable=longChain` since it's broken.

**Comment by adamdecaf** [comment]
`-disable=longChain` still panics. Removing `-withExperiemntal` works though.

Here's another panic:

```
C:\Users\adam\go\bin>gocritic.exe check-project -enable=all -withExperimental -disable=longChain ..\src\github.com\moov-io\ach
fatal error: concurrent map writes
fatal error: concurrent map iteration and map write

goroutine 1109 [running]:
runtime.throw(0x85c0e0, 0x15)
        C:/Go/src/runtime/panic.go:608 +0x79 fp=0xc000183de0 sp=0xc000183db0 pc=0x42cd99
runtime.mapassign_fast64ptr(0x7da860, 0xc00825b920, 0xc0089976e0, 0xc00601bdf8)
        C:/Go/src/runtime/map_fast64.go:187 +0x32f fp=0xc000183e20 sp=0xc000183de0 pc=0x4111ef
github.com/go-critic/go-critic/lint.resolvePkgObjects(0xc013047540, 0xc003c95500)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/lint/lint_private.go:208 +0x287 fp=0xc000183eb0 sp=0xc000183e20 pc=0x762cf7
github.com/go-critic/go-critic/lint.(*Checker).Check(0xc0130ea2d0, 0xc003c95500, 0xc0130779b0, 0xc0130ea2d0, 0x0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/lint/lint.go:96 +0xc6 fp=0xc000183ed0 sp=0xc000183eb0 pc=0x761f36
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile.func1(0xc0130779b0, 0xc003c95500, 0xc0000d5dc0, 0xc0130ea2d0)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:290 +0x9b fp=0xc000183fc0 sp=0xc000183ed0 pc=0x78065b
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000183fc8 sp=0xc000183fc0 pc=0x456af1
created by github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:272 +0xb3

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0130779b8)
        C:/Go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc0130779b0)
        C:/Go/src/sync/waitgroup.go:130 +0x6b
github.com/go-critic/go-critic/cmd/criticize.(*linter).checkFile(0xc0000d5dc0, 0xc003c95500)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:300 +0xde
github.com/go-critic/go-critic/cmd/criticize.(*linter).CheckPackage(0xc0000d5dc0, 0xc00008c030, 0x29)
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:241 +0x1bd
github.com/go-critic/go-critic/cmd/criticize.Main()
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/criticize/main.go:102 +0xd4
main.main()
        C:/Users/adam/go/src/github.com/go-critic/go-critic/cmd/gocritic/main.go:68 +0x1c0
```

**Comment by Quasilyte** [comment]
@adamdecaf, concurrent map access is already fixed in referencing PR. :)
I just recommended to avoid using `longChain` checker since it gives no good advices.

**Comment by Quasilyte** [comment]
There are many interesting checkers among experimental, but the others are not suitable for real use yet.

**Comment by adamdecaf** [comment]
Awesome! I was just noting that even with `-disable=loginChain` there was still a panic.
