### ISSUE TITLE
Need to check that imported from stdlib in dupArg

### ISSUE THREAD

**Issue by jirfag** [go-critic/go-critic#842]
Got crash in [ferret](https://github.com/MontFerret/ferret):
```
~/go/src/github.com/MontFerret/ferret/pkg/stdlib/strings (master *)$ gocritic check ./...
dupArg: error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1164 [running]:
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).checkFile.func1.1(0xc005b285a0, 0xc0061513c0)
        /Users/denis/go/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:140 +0x15c
panic(0x42f3bc0, 0x45c7020)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/go-critic/go-critic/checkers.init.17.func1.1.1(0xc0055bab00, 0xc00603bb00)
        /Users/denis/go/src/github.com/go-critic/go-critic/checkers/dupArg_checker.go:26 +0x8b
github.com/go-critic/go-critic/checkers.(*dupArgChecker).VisitExpr(0xc00645c480, 0x43b9a80, 0xc0055bab00)
        /Users/denis/go/src/github.com/go-critic/go-critic/checkers/dupArg_checker.go:111 +0xca
github.com/go-lintpack/lintpack/astwalk.(*exprWalker).WalkFile.func1(0x43b4900, 0xc0055bab00, 0xc004c73c01)
        /Users/denis/go/src/github.com/go-lintpack/lintpack/astwalk/expr_walker.go:23 +0x7f
go/ast.inspector.Visit(0xc00629dda0, 0x43b4900, 0xc0055bab00, 0x43b3aa0, 0xc00629dda0)
...
```

because of `strings.Contains` where `strings` is `github.com/MontFerret/ferret/pkg/stdlib/strings`, therefore 1 arg is allowed.

We need to check that `strings` here is from stdlib of go. Also, may be needed for other checkers.

**Comment by quasilyte** [comment]
> Also, may be needed for other checkers.

Yep. That was there for quite a long time. I'll try to fix this exact issue today and take a look into other similar issues in other checkers in near time.

**Comment by jirfag** [comment]
thank you for the fix!
