### ISSUE TITLE
panic when running check-project

### ISSUE THREAD

**Issue by kovetskiy** [go-critic/go-critic#899]
My repository doesn't have anything very specific, it's just a main package with a few pkg/ subpackages.
```
gocritic check-project ./...
check-project: walk error: <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7bffc3]

goroutine 1 [running]:
github.com/go-critic/go-critic/cmd/lintwalk.Main.func1(0xc00010e050, 0x4c, 0x0, 0x0, 0x9341c0, 0xc0000a5710, 0xc00010a1c0, 0xc0000a56b0)
        /home/operator/go/src/github.com/go-critic/go-critic/cmd/lintwalk/main.go:66 +0xc3
path/filepath.Walk(0xc00010e050, 0x4c, 0xc000064d78, 0xc0000dd180, 0x0)
        /usr/lib/go/src/path/filepath/path.go:402 +0x6a
github.com/go-critic/go-critic/cmd/lintwalk.Main()
        /home/operator/go/src/github.com/go-critic/go-critic/cmd/lintwalk/main.go:62 +0x39f
main.main()
        /home/operator/go/src/github.com/go-critic/go-critic/cmd/gocritic/main.go:61 +0x1c8
```

By the way, the documentation is outdated, there is no `check` command anymore.

**Comment by cristaloleg** [comment]
Hi, sorry for the troubles, what is you gocritic version?

**Comment by kovetskiy** [comment]
I don't know

```
 ∞  gocritic version
error: unknown sub-command: version

Supported sub-commands:
        check-package - run gocritic over specified package list
        check-project - run gocritic over specified source tree, recursively
 ∞  gocritic --version
error: unknown sub-command: --version

Supported sub-commands:
        check-package - run gocritic over specified package list
        check-project - run gocritic over specified source tree, recursively
 ∞  gocritic -v
error: unknown sub-command: -v

Supported sub-commands:
        check-package - run gocritic over specified package list
        check-project - run gocritic over specified source tree, recursively
 ∞  gocritic help
error: unknown sub-command: help

Supported sub-commands:
        check-package - run gocritic over specified package list
        check-project - run gocritic over specified source tree, recursively
 ∞  gocritic --help
error: unknown sub-command: --help

Supported sub-commands:
        check-package - run gocritic over specified package list
        check-project - run gocritic over specified source tree, recursively
```

**Comment by kovetskiy** [comment]
Looks like 95e40d8
```
 ∞ go-critic master ↕ gl
* 95e40d8 (HEAD -> master, origin/master, origin/HEAD) cmd/criticize: add withOpinionated and withExperimental flags (#279)
```

**Comment by cristaloleg** [comment]
Can you update it to something newer? 😉

**Comment by quasilyte** [comment]
Please try [v0.4.1](https://github.com/go-critic/go-critic/releases/tag/v0.4.1). We don't have `check-project` command anymore, only `check`.

**Comment by kovetskiy** [comment]
Oh, sure. My bad. I thought I don't have gocritic repository and just followed the installation guide.

Maybe it makes sense to add `-u` to `go get` here: https://github.com/go-critic/go-critic#installation

Sorry for the dumb questions, but how to install it? I did as said in the installation guide `make gocritic` and it worked, the binary appeared in the directory, but as far as I can see, `make install` doesn't work because there is no gocritic in cmd anymore

```
$ make install 
go install ./cmd/gocritic
can't load package: package ./cmd/gocritic: cannot find package "." in:
        /home/operator/go/src/github.com/go-critic/go-critic/cmd/gocritic
```

**Comment by quasilyte** [comment]
I think you'll have to put the binary somewhere by yourself. I'm not sure `make install` is made with `make gocritic` in mind. We introduced `make gocritic` somewhat recently.
