### ISSUE TITLE
unlambda panic's for variadic args

### ISSUE THREAD

**Issue by jbonzo** [go-critic/go-critic#991]
Golang version 1.15.2
Gocritic version v0.5.0

We found that gocritic's check unlambda panic's when dealing with function signatures that have variadic args

Our simple example is 
```golang
func TestSomething(t *testing.T) {
	fn :=  func(t assert.TestingT, e interface{}, a interface{}, _ ...interface{}) bool {
		return assert.Equal(t, e, a)
	}

	fn(t, "apples", "oranges")
}
```

when we run `gocritic check` on the package we get

```
unlambda: error: runtime error: index out of range [3] with length 3
panic: runtime error: index out of range [3] with length 3 [recovered]
        panic: runtime error: index out of range [3] with length 3

goroutine 2558 [running]:
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1.1(0xc0005bcc10, 0xc000f35b00)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/framework/lintmain/internal/check/check.go:142 +0x15b
panic(0x43dde40, 0xc0007b22e0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
github.com/go-critic/go-critic/checkers.(*unlambdaChecker).VisitExpr(0xc00091ec00, 0x4499060, 0xc000258780)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/checkers/unlambda_checker.go:65 +0x483
github.com/go-critic/go-critic/checkers/internal/astwalk.(*exprWalker).WalkFile.func1(0x4492c60, 0xc000258780, 0x400b901)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/checkers/internal/astwalk/expr_walker.go:23 +0x7f
go/ast.inspector.Visit(0xc00139c820, 0x4492c60, 0xc000258780, 0x44915c0, 0xc00139c820)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x44915c0, 0xc00139c820, 0x4492c60, 0xc000258780)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkExprList(0x44915c0, 0xc00139c820, 0xc000258790, 0x1, 0x1)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:26 +0x9e
go/ast.Walk(0x44915c0, 0xc00139c820, 0x4492620, 0xc0003d3cc0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:207 +0x214f
go/ast.walkStmtList(0x44915c0, 0xc00139c820, 0xc000dd5000, 0x2, 0x2)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:32 +0x9e
go/ast.Walk(0x44915c0, 0xc00139c820, 0x44927a0, 0xc000262ea0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:224 +0x1adf
go/ast.Walk(0x44915c0, 0xc00139c820, 0x4492c20, 0xc000262ed0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:344 +0xd98
go/ast.Inspect(...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/go/ast/walk.go:385
github.com/go-critic/go-critic/checkers/internal/astwalk.(*exprWalker).WalkFile(0xc00091ec10, 0xc001108400)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/checkers/internal/astwalk/expr_walker.go:21 +0x12c
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/framework/linter/lintpack.go:125
github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile.func1(0xc0005bcc10, 0xc001108400, 0xc001082000, 0x22, 0x22, 0x1e, 0xc000f35b00)
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/framework/lintmain/internal/check/check.go:150 +0xa2
created by github.com/go-critic/go-critic/framework/lintmain/internal/check.(*program).checkFile
        /Users/aperson/pkg/mod/github.com/go-critic/go-critic@v0.5.2/framework/lintmain/internal/check/check.go:132 +0x120

```

**Comment by quasilyte** [comment]
Would you like to submit a fix for this or should I go ahead? :)

**Comment by jbonzo** [comment]
> Would you like to submit a fix for this or should I go ahead? :)

I would have no idea where to start so please feel free!
